### ISSUE TITLE
bisa ini tambah column price PR - saat mau merge PR

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#18]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/96053043/157350284-d44f44e7-6b49-49af-b6d2-f53dd1ccb1ff.png">

**Comment by kevinsunjaya** [comment]
<img width="1366" alt="Screen Shot 2022-03-23 at 23 18 27" src="https://user-images.githubusercontent.com/96053043/159747278-2e0ac35b-3245-4e61-8b58-1a821996a3e3.png">



ini minsoo tambah kolom , disini bisa??

**Comment by 1ocate** [comment]
untuk itu common or for winsoft?

**Comment by 1ocate** [comment]
![Screen Shot 2023-04-26 at 11 18 48 PM](https://user-images.githubusercontent.com/29521447/234605164-223694c3-6dc1-4738-985a-64ffa08d1fab.png)

Coba check ya

**Comment by kevinsunjaya** [comment]
thanks minsoo :)
