### ISSUE TITLE
sorting use -> field => amount tax -> di Vendor invoice , - cannot works 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#23]
![image](https://user-images.githubusercontent.com/96053043/179945605-93bca9ae-69ff-453b-9f69-22c876627b15.png)

![image](https://user-images.githubusercontent.com/96053043/179945746-62c8022b-66fc-4a19-b344-7561daab7450.png)

klik ini , tapi tidak working

**Comment by 1ocate** [comment]
coba check
