### ISSUE TITLE
product details - harga per pcs , bisa minsoo ? 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#26]
https://erp.winsoft.co.id/product/stats/commande.php?id=1865

product click detail -> related items -> purchase order / sales orders / invoices -> keluar nya harga total . bukan harga per pcs

![image](https://user-images.githubusercontent.com/96053043/197989968-f6dd8bfc-7d75-41b3-aeb8-f979839eb854.png)

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/96053043/197990494-608ca943-fac1-405a-97e0-e67882283e28.png">

**Comment by 1ocate** [comment]
please checking thank you.

**Comment by kevinsunjaya** [comment]
okay minsoo, boleh dikategori -> product click detail -> related items -> dimenu =>  purchase order and  invoices juga?? 

![image](https://user-images.githubusercontent.com/96053043/234747250-a5448d36-9173-40c3-958f-663b159358e9.png)


![image](https://user-images.githubusercontent.com/96053043/234747298-229b2547-ed0e-48fb-a575-a8dce64f8a1f.png)


thanks minsoo ...

**Comment by 1ocate** [comment]
@kevinsunjaya OK I will check

**Comment by 1ocate** [comment]
#33 Done
Please check @kevinsunjaya

**Comment by kevinsunjaya** [comment]
thanks minsoo. semua suda clear :)
