### ISSUE TITLE
RCP -searching filter cannot work  -Menu product -> Reception -> List

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#31]
![image](https://user-images.githubusercontent.com/96053043/234747552-35add6a4-34cf-4827-9fc9-056619b4e4f8.png)

https://erp.winsoft.co.id/custom/vptop/reception_list.php

**Comment by 1ocate** [comment]
@kevinsunjaya coba check

**Comment by kevinsunjaya** [comment]
Thanks minsoo . Done
