### ISSUE TITLE
proposal setelah di merge -> number in PDF -> not ascending 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#36]
https://erp.winsoft.co.id/comm/propal/card.php?id=4947&action=confirm_validate&confirm=yes&token=e942119fd1ef40e426ebc23a2cfcf41c

![image](https://user-images.githubusercontent.com/96053043/235888323-2d374315-822e-4638-b7a6-ab9b68634247.png)

**Comment by 1ocate** [comment]
@kevinsunjaya 
please test.
Thank you.

**Comment by kevinsunjaya** [comment]
thanks minsoo
