### ISSUE TITLE
Minsoo ini saya mau tambah di sini. Tidak bisa ya??  

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#40]
https://erp.winsoft.co.id/commande/card.php?id=16857&save_lastsearch_values=1

![Screenshot_20231014_093211_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/c6b75b07-2151-404d-aa4b-eec008601628)

![Screenshot_20231014_093203_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/6db76797-53f7-4812-bf18-34104c0acb7c)

Mau nambahin ini minsoo
Di field = requirement = 

Saya coba rubah
https://erp.winsoft.co.id/admin/order_extrafields.php

![Screenshot_20231014_093454_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/5496922a-f5b8-411f-8b2a-a31ec48168b6)

Tapi eror

![Screenshot_20231014_093629_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/728f8f9b-c590-4bac-b5cf-00de451860c7)

Boleh bantu tambahkan minsoo 

3 field lagi

![Screenshot_20231014_093756_Gallery.jpg](https://github.com/wglobalindo/erp/assets/96053043/e6a9113f-ab77-4f3e-a1db-93840dbd9c00)

**Comment by 1ocate** [comment]
![image](https://github.com/wglobalindo/erp/assets/29521447/d1d35618-972a-42a7-aab9-039f9a3e46f3)
please check
https://erp.winsoft.co.id/admin/order_extrafields.php

coba rubah juga ya
