### ISSUE TITLE
Minsoo boleh bantu . Di sdr.winsoft.co.id

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#41]
Kode product barang ada didatabase

![Screenshot_20231014_100633_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/24af5943-88c2-40ef-8902-a0038ffc6465)

Tapi saat buat co

Kode productnya tidak ada

![Screenshot_20231014_100503_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/cf8654ea-7572-4851-9591-f0ad2ba4fe04)

![Screenshot_20231014_100445_Chrome.jpg](https://github.com/wglobalindo/erp/assets/96053043/b888a3f2-36e3-42a3-8ebc-619e5283f950)

Thanks minsoo

**Comment by 1ocate** [comment]
![Screen Shot 2023-10-28 at 10 38 33 PM](https://github.com/wglobalindo/erp/assets/29521447/2f177c20-dd06-4c44-8974-0e99e9c449c3)
https://sdr.winsoft.co.id/product/admin/product.php

After that value change (1000 -> 0) display no problem
