### ISSUE TITLE
minsoo bisa bantu cek erorr ini? unit - eror unit 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#43]
0,Pcs
1,Set
2,Dozen
3,Botol
4,Box
5,Roll
6,Meter
7,Liter
8,Pack
9,Drum

![image](https://github.com/wglobalindo/erp/assets/96053043/a288652c-319c-4ee9-bf8f-0219da836980)

https://erp.winsoft.co.id/admin/orderdet_extrafields.php?action=edit&token=9ba32cc72b28f6eb3115c31451074c36&attrname=unit#formeditextrafield

tapi setelah di print surat jalan, 

Unit nya beda keluarnya 

![image](https://github.com/wglobalindo/erp/assets/96053043/a39fe93e-b4ca-49ef-b90f-f8f48608d468)

**keluarnya UNITNYA. = PAIR ???**

![image](https://github.com/wglobalindo/erp/assets/96053043/e65041c7-b439-4bb2-aaef-05ab0f3df8fd)

thanks minsoo

**Comment by 1ocate** [comment]
#45 
fix please check
