### ISSUE TITLE
minsoo -> for erp winsoft -> everytime invoice mau hapus, saya need to ask minsoo, can my user get permission to delete invoice or product?

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_winsoft#7]
minsoo -> for erp winsoft -> everytime invoice mau hapus, saya need to ask minsoo,

 can my user account in ERP Winsoft ->  get permission to delete invoice or product? -> only me

**Comment by 1ocate** [comment]
What mean product? 
that can't remove?

**Comment by 1ocate** [comment]
Add value to here [Home -> Setup -> Other Setup](https://erp.winsoft.co.id/admin/const.php?mainmenu=home&leftmenu=setup&idmenu=5582)

```
INVOICE_CAN_ALWAYS_BE_REMOVED = 1
```

INVOICE_CAN_ALWAYS_BE_REMOVED 

> ► Allow to always delete invoices (even if invoice is not last one). Note: If the module "BlockedLog" is active (required by some countries for legal reason), this will not change content of archived logs tracked by this module. By definition there is no way to change or remove archived records. It will just update data in your application and a new record to track your change into the read-only archive log.

More information from  here [Setup Other](https://wiki.dolibarr.org/index.php?title=Setup_Other).

**Comment by 1ocate** [comment]
@kevinsunjaya Already try?

**Comment by kevinsunjaya** [comment]
yes minsoo,
